In [1]:
import numpy as np

In [2]:
 array = np.array([1,2,3])
print(array)

[1 2 3]


In [3]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2.shape)

(15,)


In [4]:
a = array2.reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
print("Shape:",a.shape)

Shape: (3, 5)


In [6]:
print("Dimension:",a.ndim)

Dimension: 2


In [7]:
print("Data Type:",a.dtype.name)

Data Type: int32


In [8]:
print("size:",a.size)

size: 15


In [9]:
print("type:",type(a))

type: <class 'numpy.ndarray'>


In [11]:
array3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [12]:
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
array3.shape

(3, 4)

In [14]:
zeros = np.zeros((3,4))

In [15]:
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
np.empty((4,5))

array([[4.67296746e-307, 1.69121096e-306, 7.56587584e-307,
        1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.33511290e-306, 1.78019082e-306],
       [8.45559303e-307, 8.06613465e-308, 6.89810244e-307,
        1.22387550e-307, 2.22522596e-306]])

In [19]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
a = np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [21]:
a = np.array([1,2,3,])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [26]:
liste = [1,2,3,4]
array = np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [27]:
a = np.array([1,2,3])

In [28]:
b=a
c=a

In [29]:
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [ ]:
a[0]=5

In [31]:
d = a.copy()
print(d)

[5 2 3]


In [32]:
d

array([5, 2, 3])

In [33]:
a = np.array([1,2,3,4,5,6,7])

In [34]:
a[0]

1

In [35]:
a[0:4] #(inclusive, exclusive)

array([1, 2, 3, 4])

In [36]:
a[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [38]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
print(b[1,1])

7


In [40]:
print(b[:,1])

[2 7]


In [41]:
b[1,:]

array([ 6,  7,  8,  9, 10])

In [42]:
b[1,1:4]

array([7, 8, 9])

In [43]:
b[-1,:]

array([ 6,  7,  8,  9, 10])

In [44]:
b[:,-1]

array([ 5, 10])

In [45]:
b = b.ravel()
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
b.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])